local handler = require("event_handler")

handler.add_lib(require("scripts.freeplay"))
handler.add_lib(require("scripts.indestructible"))
handler.add_libraries(require("scripts.constructors"))
handler.add_libraries(require("scripts.miners"))
handler.add_libraries(require("scripts.special"))
handler.add_libraries(require("scripts.logistics"))
handler.add_libraries(require("scripts.organisation"))
handler.add_libraries(require("scripts.weapons"))
handler.add_lib(require("scripts.lualib.resource-spawner"))
handler.add_lib(require("scripts.lualib.resource-scanner"))
handler.add_lib(require("scripts.lualib.power-trip"))
handler.add_lib(require("scripts.map-tweaks"))
