require("prototypes.constructors.craft-bench")
require("prototypes.constructors.equipment-workshop")
require("prototypes.constructors.smelter")
require("prototypes.constructors.constructor")
require("prototypes.constructors.assembler")
