require("prototypes.creatures.fluffy-tailed-hog")
require("prototypes.creatures.alpha-hog")
require("prototypes.creatures.spitter")
require("prototypes.creatures.alpha-spitter")
require("prototypes.creatures.spore-flower")
require("prototypes.creatures.gas-emitter")
require("prototypes.creatures.flying-crab")

require("prototypes.creatures.lizard-doggo")
require("prototypes.creatures.power-slugs")
