require("prototypes.logistics.loader-inserter")
require("prototypes.logistics.loader-conveyor")
require("prototypes.logistics.conveyor-belt-mk-1")
require("prototypes.logistics.pipe")
require("prototypes.logistics.pipe-to-ground")
require("prototypes.logistics.pump")
require("prototypes.logistics.personal-storage-box")
