require("prototypes.logistics.loader-inserter")
require("prototypes.logistics.loader-conveyor")
require("prototypes.logistics.conveyor-belt-mk-1")
require("prototypes.logistics.conveyor-belt-mk-2")
require("prototypes.logistics.conveyor-belt-mk-3")
require("prototypes.logistics.conveyor-belt-mk-4")
-- require("prototypes.logistics.conveyor-belt-mk-5")
require("prototypes.logistics.conveyor-lift-mk-1")
require("prototypes.logistics.conveyor-lift-mk-2")
require("prototypes.logistics.conveyor-lift-mk-3")
require("prototypes.logistics.conveyor-lift-mk-4")
-- require("prototypes.logistics.conveyor-lift-mk-5")
require("prototypes.logistics.conveyor-splitter")
require("prototypes.logistics.conveyor-merger")
require("prototypes.logistics.pipe")
require("prototypes.logistics.pipe-to-ground")
require("prototypes.logistics.pump")
require("prototypes.logistics.foundation")
require("prototypes.logistics.wall")
