require("prototypes.miners.portable-miner")
require("prototypes.miners.miners")
require("prototypes.miners.water-extractor")
require("prototypes.miners.oil-extractor")
require("prototypes.miners.resource-well-pressuriser")
require("prototypes.miners.resource-well-extractor")
