require("prototypes.organisation.personal-storage-box")
require("prototypes.organisation.storage-container")
require("prototypes.organisation.lookout-tower")
require("prototypes.organisation.map-marker")
require("prototypes.organisation.object-scanner")
