require("prototypes.power.biomass-burner-hub")
require("prototypes.power.biomass-burner")
require("prototypes.power.coal-generator")
require("prototypes.power.fuel-generator")
require("prototypes.power.power-pole-mk-1")
