require("prototypes.special.the-hub")
require("prototypes.special.ficsit-freighter")
require("prototypes.special.mam")
require("prototypes.special.space-elevator")
require("prototypes.special.omnilab")
