require("prototypes.special.the-hub")
require("prototypes.special.mam")
require("prototypes.special.space-elevator")
require("prototypes.special.awesome-sink")
require("prototypes.special.awesome-shop")
require("prototypes.special.omnilab")
require("prototypes.special.crash-sites")
