require("prototypes.weapons.xeno-zapper")
require("prototypes.weapons.xeno-basher")
require("prototypes.weapons.rebar-gun")
require("prototypes.weapons.rifle")
require("prototypes.weapons.chainsaw")
